"""■ B — the feature table is causal, it is documented, and it is built on the side that has data.

Ticket 07's three failure modes, in the order they cost the most:

  * **A feature that peeks forward.** This repo has already been bitten: the first pass found
    velocity windows reading rows from the future, and most of the apparent signal was leakage.
    So causality gets property tests and a brute-force cross-check, not a code review.
  * **A feature that is quietly empty.** PaySim has no sender history, so a third of this table
    is structurally dead on that anchor. A dead column reads exactly like a feature the model
    has, and it is not one — so the emptiness is measured, not assumed.
  * **A feature nobody can explain.** Every column carries a one-line rationale in the registry
    and `docs/features.md` is generated from it, so the two cannot drift apart.

The brute-force reference below is the load-bearing test. `FeatureBuilder` computes every column
by bisecting prefix-summed arrays, which is fast and is exactly the kind of code that goes wrong
by one index in a way no unit test notices. `reference_rows` computes the same 56 numbers the
obvious slow way — filter the prior rows, then add them up — and the two must agree exactly.
"""

from __future__ import annotations

import time
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import yaml

from afl.contract.schema import Rail, Transaction
from afl.data import loaders
from afl.defend import explain
from afl.defend.features import (
    DWELL_WINDOW_S,
    FORBIDDEN,
    NEVER,
    VELOCITY_WINDOWS_S,
    FeatureBuilder,
    assert_no_forbidden_columns,
    feature_names,
    feature_specs,
)

T0 = datetime(2024, 1, 1)

#: Floor for the real-anchor timing test. Ten times slower than measured, so it catches a
#: quadratic regression and never fires on a busy laptop. The measured numbers live in
#: `docs/features.md`, regenerated by `make features`.
MIN_ROWS_PER_SECOND = 10_000


def txn(txn_id: str, offset_s: float, src: str, dst: str, amount: float = 100.0, **kw):
    return Transaction(
        txn_id=txn_id,
        ts=T0 + timedelta(seconds=offset_s),
        src=src,
        dst=dst,
        amount=amount,
        rail=kw.pop("rail", Rail.A2A),
        **kw,
    )


def random_txns(n: int, seed: int, offset_s: float = 0.0, prefix: str = "t", entities: int = 10):
    """Dense random traffic over a small population — every entity both pays and is paid."""
    rng = np.random.default_rng(seed)
    ids = [f"e{i}" for i in range(entities)]
    rows = []
    for i in range(n):
        src, dst = str(rng.choice(ids)), str(rng.choice(ids))
        if src == dst:
            dst = ids[-1] if src != ids[-1] else ids[0]
        rows.append(
            Transaction(
                txn_id=f"{prefix}{i:05d}",
                ts=T0 + timedelta(seconds=offset_s + float(rng.integers(0, 600_000))),
                src=src,
                dst=dst,
                amount=round(float(rng.lognormal(5.0, 1.2)), 2),
                rail=[Rail.A2A, Rail.CARD, Rail.UPI][int(rng.integers(0, 3))],
                device_id=f"dev{int(rng.integers(0, 4))}" if rng.random() < 0.8 else None,
                is_fraud=bool(rng.random() < 0.1),
            )
        )
    return rows


# ── the reference implementation ────────────────────────────────────────────────
def reference_rows(txns: list[Transaction], windows_s=VELOCITY_WINDOWS_S) -> np.ndarray:
    """The same 56 features, computed the obvious way: filter the prior rows and add them up.

    Deliberately O(n^2) and deliberately dumb. Its whole value is that it shares no code with
    the implementation, so an off-by-one in a bisect shows up as a number, not as a silence.
    """
    order = sorted(range(len(txns)), key=lambda i: txns[i].ts)
    out: list[list[float]] = [[]] * len(txns)
    seen: list[Transaction] = []
    for i in order:
        t = txns[i]
        ts = t.ts.timestamp()
        prior = [p for p in seen if p.ts.timestamp() <= ts]
        s_out = [(p.ts.timestamp(), p.amount, p.dst) for p in prior if p.src == t.src]
        s_in = [(p.ts.timestamp(), p.amount, p.src) for p in prior if p.dst == t.src]
        d_in = [(p.ts.timestamp(), p.amount, p.src) for p in prior if p.dst == t.dst]
        d_out = [(p.ts.timestamp(), p.amount, p.dst) for p in prior if p.src == t.dst]
        pair = [p.ts.timestamp() for p in prior if p.src == t.src and p.dst == t.dst]

        def window(events, w, now=ts):
            return [e for e in events if now - w <= e[0] <= now]

        hour, weekday, amount = t.ts.hour, t.ts.weekday(), t.amount
        f = [
            amount,
            float(np.log1p(amount)),
            hour + t.ts.minute / 60.0,
            float(hour < 6),
            float(weekday),
            float(weekday >= 5),
            float(t.rail.value == "card"),
            float(t.rail.value == "upi"),
            float(t.rail.value == "a2a"),
            float(abs(amount - round(amount, -2)) < 1e-9),
            float(9_000 <= amount < 10_000),
            float(900 <= amount < 1_000),
        ]
        for w in windows_s:
            r = window(s_out, w)
            f += [float(len(r)), sum(e[1] for e in r), float(len({e[2] for e in r}))]

        amounts = [e[1] for e in s_out]
        mean = sum(amounts) / len(amounts) if amounts else 0.0
        std = float(np.std(amounts)) if len(amounts) > 1 else 0.0
        f += [
            float(len(amounts)),
            ts - max(e[0] for e in s_out) if s_out else NEVER,
            mean,
            std,
            (amount - mean) / std if std > 0 else 0.0,
            amount / mean if mean else 1.0,
            float(len({e[2] for e in s_out})),
            ts - min(e[0] for e in s_out + s_in) if (s_out or s_in) else NEVER,
        ]
        for w in windows_s:
            r = window(d_in, w)
            f += [float(len(r)), sum(e[1] for e in r), float(len({e[2] for e in r}))]

        in_amounts = [e[1] for e in d_in]
        mean_in = sum(in_amounts) / len(in_amounts) if in_amounts else 0.0
        std_in = float(np.std(in_amounts)) if len(in_amounts) > 1 else 0.0
        f += [
            float(len(in_amounts)),
            float(len({e[2] for e in d_in})),
            ts - max(e[0] for e in d_in) if d_in else NEVER,
            mean_in,
            (amount - mean_in) / std_in if std_in > 0 else 0.0,
            float(not d_in),
            ts - min(e[0] for e in d_in + d_out) if (d_in or d_out) else NEVER,
        ]

        recent_in = window(s_in, DWELL_WINDOW_S)
        in_sum = sum(e[1] for e in recent_in)
        out_sum = sum(e[1] for e in window(s_out, DWELL_WINDOW_S))
        f += [
            float(len(recent_in)),
            in_sum,
            ts - max(e[0] for e in s_in) if s_in else NEVER,
            out_sum / in_sum if in_sum > 0 else 0.0,
            float(len(window(d_out, DWELL_WINDOW_S))),
        ]
        f += [float(not pair), float(len(pair)), ts - max(pair) if pair else NEVER]

        devices: dict[str, float] = {}
        for p in prior:
            if p.src == t.src and p.device_id:
                devices[p.device_id] = min(devices.get(p.device_id, 1e18), p.ts.timestamp())
        first = devices.get(t.device_id) if t.device_id else None
        f += [
            float(len(devices)),
            float(t.device_id is not None and first is None),
            ts - first if first is not None else NEVER,
        ]
        out[i] = f
        seen.append(t)
    return np.array(out, dtype="float64")


def assert_matches_reference(X: pd.DataFrame, expected: np.ndarray, names: list[str]) -> None:
    got = X.to_numpy()
    bad = ~np.isclose(got, expected, rtol=1e-9, atol=1e-9)
    if bad.any():
        col = int(np.unique(np.where(bad)[1])[0])
        row = int(np.where(bad[:, col])[0][0])
        raise AssertionError(
            f"{int(bad.sum())} value(s) disagree with the reference, "
            f"first at row {row} column {names[col]!r}: {got[row, col]!r} != {expected[row, col]!r}"
        )


def test_every_column_matches_a_brute_force_reference():
    """The load-bearing test: the fast path and the obvious path agree on all 56 columns."""
    rows = random_txns(400, seed=7)
    builder = FeatureBuilder()
    assert_matches_reference(builder.transform(rows), reference_rows(rows), builder.feature_names)


def test_the_reference_also_holds_when_the_builder_carries_state_between_batches():
    """Statefulness must not be a second, subtly different implementation."""
    first, second = random_txns(200, seed=11), random_txns(200, seed=12, prefix="u")
    builder = FeatureBuilder(stateful=True)
    builder.transform(first)
    X = builder.transform(second)
    expected = reference_rows(first + second)[len(first) :]
    assert_matches_reference(X, expected, builder.feature_names)


# ── causality ───────────────────────────────────────────────────────────────────
def test_a_feature_does_not_change_when_later_rows_are_appended():
    """The ticket's property test, over random traffic rather than one hand-picked row.

    This is the failure mode the whole module exists to avoid: an offline table that looks
    excellent because it was built with knowledge no scorer would have had.
    """
    history = random_txns(150, seed=21)
    probe = random_txns(50, seed=23, prefix="p")  # same window as the history
    later = random_txns(150, seed=22, offset_s=700_000, prefix="z")  # strictly afterwards

    builder = FeatureBuilder(stateful=True)
    builder.transform(history, update=True)
    before = builder.transform(probe, update=False)

    builder.transform(later, update=True)  # the future arrives
    after = builder.transform(probe, update=False)

    assert_matches_reference(after, before.to_numpy(), builder.feature_names)


def test_one_probe_row_is_unmoved_by_everything_that_happens_after_it():
    builder = FeatureBuilder(stateful=True)
    history = [txn(f"h{i}", i * 600, "s1", "d1", 100.0 + i) for i in range(8)]
    probe = txn("probe", 9 * 600, "s1", "d1", 250.0)
    builder.transform(history, update=True)
    before = builder.transform([probe], update=False)

    builder.transform([txn(f"late{i}", 20_000 + i * 600, "s1", "d1") for i in range(6)])
    assert builder.transform([probe], update=False).equals(before)


def test_scoring_does_not_mutate_feature_state():
    """Ask the same question twice, get the same answer — even with a stateful builder."""
    builder = FeatureBuilder(stateful=True)
    rows = random_txns(120, seed=31)
    builder.transform(rows, update=True)

    first = builder.transform(rows, update=False)
    second = builder.transform(rows, update=False)
    assert first.equals(second)

    # and the committed history is byte-identical afterwards, not merely close
    committed = builder.transform(random_txns(40, seed=32, prefix="q"), update=True)
    builder_b = FeatureBuilder(stateful=True)
    builder_b.transform(rows, update=True)
    assert committed.equals(builder_b.transform(random_txns(40, seed=32, prefix="q")))


def test_a_batch_that_predates_the_history_is_still_causal():
    """A replay buffer replays old rows. The out-of-order path has to be exact, not approximate."""
    late, early = random_txns(120, seed=41, offset_s=900_000), random_txns(120, seed=42)
    builder = FeatureBuilder(stateful=True)
    builder.transform(late, update=True)
    X = builder.transform(early, update=True)
    expected = reference_rows(late + early)[len(late) :]
    assert_matches_reference(X, expected, builder.feature_names)


def test_rows_inside_a_scored_batch_still_see_the_rows_before_them():
    """By the time the second payment of a burst is scored in production, the first has happened."""
    builder = FeatureBuilder(stateful=True)
    builder.transform([txn("seed0", 0, "other", "elsewhere")], update=True)
    burst = [txn(f"b{i}", 100 + i * 10, "s1", f"d{i}") for i in range(5)]
    X = builder.transform(burst, update=False)
    assert X["src_out_cnt_3600s"].tolist() == [0.0, 1.0, 2.0, 3.0, 4.0]


# ── graph features are as-of the row, not over the finished graph ───────────────
def test_graph_features_are_computed_as_of_the_rows_timestamp():
    """In-degree at 09:00 must not know about the edges that arrive at 17:00."""
    builder = FeatureBuilder(stateful=True)
    early = [txn(f"e{i}", i, f"payer{i}", "collector") for i in range(3)]
    probe = txn("probe", 100, "payer9", "collector")
    builder.transform(early, update=True)
    before = builder.transform([probe], update=False)
    assert before["dst_in_degree"].iloc[0] == 3.0

    builder.transform([txn(f"l{i}", 10_000 + i, f"payerL{i}", "collector") for i in range(20)])
    after = builder.transform([probe], update=False)
    assert after["dst_in_degree"].iloc[0] == 3.0, "in-degree grew with edges from the future"
    assert builder.transform([txn("now", 20_000, "x", "collector")])["dst_in_degree"].iloc[0] == 23


def test_in_degree_counts_distinct_payers_not_payments():
    """The reason code says 'how many accounts have ever paid this beneficiary'. It has to."""
    builder = FeatureBuilder()
    rows = [txn(f"r{i}", i * 60, "one_payer", "shop") for i in range(5)]
    rows.append(txn("other", 600, "another_payer", "shop"))
    X = builder.transform(rows)
    assert X.loc["other", "dst_in_degree"] == 1.0  # only `one_payer` has paid before
    assert X.loc["other", "dst_in_txn_count"] == 5.0  # but it paid five times


# ── direction: the bug this module was rebuilt to remove ────────────────────────
def test_fan_in_and_fan_out_are_not_the_same_number():
    """One shared history per entity made 'sent' and 'received' indistinguishable."""
    builder = FeatureBuilder()
    rows = [txn(f"in{i}", i * 60, f"payer{i}", "mule") for i in range(6)]
    rows.append(txn("probe", 500, "mule", "cashout"))
    X = builder.transform(rows)
    assert X.loc["probe", "src_in_cnt_3600s"] == 6.0, "the mule received six payments"
    assert X.loc["probe", "src_out_cnt_3600s"] == 0.0, "and had sent none"


def test_the_beneficiary_side_works_when_the_sender_has_no_history_at_all():
    """The PaySim case: `nameOrig` is unique per row, so `src_*` is empty by construction."""
    builder = FeatureBuilder()
    rows = [txn(f"p{i}", i * 60, f"once_only_{i}", "collector", 500.0) for i in range(10)]
    X = builder.transform(rows)
    assert (X["src_out_cnt_3600s"] == 0).all(), "no sender in this traffic has a past"
    assert X["dst_in_cnt_3600s"].tolist() == [float(i) for i in range(10)]
    assert X["dst_in_uniq_src_3600s"].tolist() == [float(i) for i in range(10)]
    assert X["dst_in_degree"].tolist() == [float(i) for i in range(10)]


def test_dwell_time_measures_the_gap_between_money_arriving_and_leaving():
    """The knob C3 trades detectability against: instant pass-through is loud."""
    builder = FeatureBuilder()
    X = builder.transform(
        [
            txn("inbound", 0, "victim", "mule", 10_000.0),
            txn("onward", 30, "mule", "cashout", 10_000.0),
        ]
    )
    assert X.loc["onward", "src_seconds_since_last_in"] == 30.0
    assert X.loc["onward", "src_passthrough_ratio_3600s"] == 0.0  # nothing sent yet, all held
    assert X.loc["inbound", "src_seconds_since_last_in"] == NEVER


def test_the_pass_through_ratio_reaches_one_when_everything_is_forwarded():
    builder = FeatureBuilder()
    rows = [
        txn("in1", 0, "victim", "mule", 5_000.0),
        txn("out1", 10, "mule", "cashout", 5_000.0),
        txn("in2", 20, "victim2", "mule", 5_000.0),
        txn("probe", 30, "mule", "cashout", 1.0),
    ]
    X = builder.transform(rows)
    assert X.loc["probe", "src_passthrough_ratio_3600s"] == pytest.approx(0.5)
    assert X.loc["probe", "src_in_sum_3600s"] == pytest.approx(10_000.0)


def test_first_ever_payment_to_a_payee_is_flagged_once_and_then_never_again():
    """C2's tell, and the one relationship feature that needs no history to be informative."""
    builder = FeatureBuilder()
    X = builder.transform([txn(f"p{i}", i * 3_600, "victim", "scammer") for i in range(3)])
    assert X["pair_is_first_payment"].tolist() == [1.0, 0.0, 0.0]
    assert X["pair_txn_count"].tolist() == [0.0, 1.0, 2.0]
    assert X["pair_seconds_since_last"].tolist() == [NEVER, 3_600.0, 3_600.0]
    assert X["dst_is_first_ever_inbound"].tolist() == [1.0, 0.0, 0.0]


def test_an_account_with_no_past_is_marked_never_rather_than_zero():
    """Zero seconds since the last payment would read as 'it just paid'. It is the opposite."""
    X = FeatureBuilder().transform([txn("first", 0, "brand_new", "somewhere")])
    for column in (
        "src_seconds_since_last_out",
        "src_seconds_since_last_in",
        "dst_seconds_since_last_in",
        "src_account_age_s",
        "dst_account_age_s",
        "pair_seconds_since_last",
    ):
        assert X[column].iloc[0] == NEVER, column


def test_the_amount_z_score_survives_an_account_that_always_pays_the_same_amount():
    """A subscription, an EMI, a salary. The naive variance turns rounding error into a signal.

    `E[x^2] - E[x]^2` over amounts of 10,000,000 has the two terms agreeing to fifteen digits, so
    what is left is noise — and `src_amount_z` divides by it. An account that has paid exactly
    the same amount forty times has a standard deviation of zero, and a detector must not be told
    that its forty-first identical payment is unusual.
    """
    builder = FeatureBuilder()
    rows = [txn(f"s{i}", i * 3_600, "payer", "biller", 10_000_000.0) for i in range(40)]
    rows.append(txn("same_again", 40 * 3_600, "payer", "biller", 10_000_000.0))
    X = builder.transform(rows)
    assert X.loc["same_again", "src_out_amount_std"] == 0.0
    assert X.loc["same_again", "src_amount_z"] == 0.0
    assert X.loc["same_again", "src_out_amount_mean"] == 10_000_000.0


def test_the_standard_deviation_is_accurate_on_large_near_constant_amounts():
    """The same trap one step less obvious: a tiny but real spread on a large amount."""
    rng = np.random.default_rng(3)
    amounts = np.abs(rng.normal(1e7, 1.0, 500)) + 0.01
    rows = [txn(f"n{i}", i * 60, "payer", "biller", float(a)) for i, a in enumerate(amounts)]
    X = FeatureBuilder().transform(rows)
    got = X.iloc[-1]["src_out_amount_std"]
    want = float(np.std(amounts[:-1]))
    assert got == pytest.approx(want, rel=1e-6), f"{got} != {want} — unstable variance is back"


# ── statefulness ────────────────────────────────────────────────────────────────
def test_stateful_carries_history_across_batches_and_stateless_does_not():
    """A mule's history does not reset because a new round began."""
    first = [txn(f"a{i}", i * 60, "mule", f"d{i}") for i in range(5)]
    second = [txn("probe", 500, "mule", "d9")]

    stateful = FeatureBuilder(stateful=True)
    stateful.transform(first, update=True)
    assert stateful.transform(second)["src_out_cnt_3600s"].iloc[0] == 5.0

    stateless = FeatureBuilder(stateful=False)
    stateless.transform(first, update=True)
    assert stateless.transform(second)["src_out_cnt_3600s"].iloc[0] == 0.0


def test_accumulation_keeps_growing_over_many_batches():
    builder = FeatureBuilder(stateful=True)
    counts = []
    for round_no in range(4):
        rows = [txn(f"r{round_no}-{i}", round_no * 100 + i, "mule", f"d{i}") for i in range(3)]
        counts.append(builder.transform(rows)["src_out_txn_count"].iloc[0])
    assert counts == [0.0, 3.0, 6.0, 9.0]


def test_an_empty_batch_returns_an_empty_table_with_the_full_column_set():
    """A round can produce nothing. The columns still have to line up with the fitted model."""
    builder = FeatureBuilder(stateful=True)
    X = builder.transform([])
    assert X.shape == (0, len(feature_names()))
    assert list(X.columns) == feature_names()
    assert builder.state_size() == {"entities": 0, "events": 0, "pairs": 0, "devices": 0}


def test_reset_forgets_everything():
    builder = FeatureBuilder(stateful=True)
    builder.transform([txn(f"a{i}", i * 60, "mule", "d1") for i in range(5)])
    builder.reset()
    assert builder.transform([txn("probe", 500, "mule", "d1")])["src_out_cnt_3600s"].iloc[0] == 0.0


# ── the answer key never reaches the model ──────────────────────────────────────
def test_no_forbidden_column_reaches_x():
    rows = random_txns(60, seed=51)
    for t in rows:
        t.vector_id, t.attack_run_id = "S1", "run-1"
    X = FeatureBuilder().transform(rows)
    assert set(FORBIDDEN) & set(X.columns) == set()
    assert X.index.name == "txn_id"  # the id identifies the row; it is not a column of it


def test_the_forbidden_column_guard_actually_fires():
    """The guard is only worth having if it is proved to fail on a table that leaks."""
    X = FeatureBuilder().transform(random_txns(20, seed=52))
    assert_no_forbidden_columns(X)
    X["is_fraud"] = 1.0
    with pytest.raises(AssertionError, match="forbidden column"):
        assert_no_forbidden_columns(X)


def test_labels_are_returned_separately_from_the_features():
    rows = random_txns(40, seed=53)
    y = FeatureBuilder.labels(rows)
    assert y.tolist() == [int(t.is_fraud) for t in rows]


def test_provenance_cannot_change_a_single_feature_value():
    """Belt and braces: two identical batches, one wearing labels, must produce one table."""
    plain = random_txns(80, seed=54)
    labelled = [t.model_copy(update={"is_fraud": True, "vector_id": "S1"}) for t in plain]
    assert FeatureBuilder().transform(plain).equals(FeatureBuilder().transform(labelled))


# ── the names, and the documentation that hangs off them ────────────────────────
def test_the_emitted_columns_are_exactly_the_registry_in_order():
    """The builder fills a positional buffer, so a registry that drifts shifts every column."""
    builder = FeatureBuilder()
    X = builder.transform(random_txns(10, seed=61))
    assert list(X.columns) == [spec.name for spec in feature_specs()]
    assert list(X.columns) == feature_names()
    assert list(X.columns) == builder.feature_names


def test_every_column_has_a_rationale_and_a_known_group():
    from afl.defend.features import FEATURE_GROUPS

    for spec in feature_specs():
        assert spec.group in FEATURE_GROUPS, f"{spec.name} sits in an undeclared group"
        assert len(spec.why.split()) >= 6, f"{spec.name} has no real rationale: {spec.why!r}"
        assert spec.why.strip().endswith("."), f"{spec.name}'s rationale is not a sentence"


def test_feature_names_are_unique_and_readable():
    names = feature_names()
    assert len(set(names)) == len(names)
    for name in names:
        assert name == name.lower() and " " not in name
        assert not any(name.startswith(bad) for bad in ("f_", "x_", "col")), name


def test_changing_the_windows_changes_the_names_and_nothing_else():
    builder = FeatureBuilder(windows_s=(60, 3_600))
    X = builder.transform(random_txns(30, seed=62))
    assert "src_out_cnt_60s" in X.columns
    assert "src_out_cnt_604800s" not in X.columns
    assert list(X.columns) == [s.name for s in feature_specs((60, 3_600))]


def test_the_reason_code_vocabulary_has_not_gone_stale():
    """Ticket 09 renders these names to an analyst. A phrase for a dropped column is a lie."""
    names = set(feature_names())
    stale = sorted(set(explain.FEATURE_PHRASES) - names)
    assert not stale, f"explain.FEATURE_PHRASES names columns that no longer exist: {stale}"


# ── what the table actually contains ────────────────────────────────────────────
def test_coverage_names_the_columns_that_are_structurally_empty():
    """The PaySim shape: senders that appear once, so the whole src block is dead."""
    builder = FeatureBuilder()
    rows = [txn(f"p{i}", i * 60, f"once_{i}", "collector", 500.0) for i in range(30)]
    coverage = builder.coverage(builder.transform(rows))

    assert coverage.loc["src_out_cnt_3600s", "dead"]
    assert not coverage.loc["dst_in_cnt_3600s", "dead"]
    assert set(coverage.columns) >= {"group", "distinct_values", "share_informative", "dead"}
    assert coverage.loc["src_seconds_since_last_out", "share_never"] == 1.0


# ── the real anchors ────────────────────────────────────────────────────────────
def anchors() -> list[dict]:
    configs = [yaml.safe_load(p.read_text()) for p in sorted(Path("config/data").glob("*.yaml"))]
    return [c for c in configs if c.get("loader")]


ANCHORS = anchors()


def anchor_present(cfg: dict) -> bool:
    root = Path(cfg["source"].get("place_in", "data/raw"))
    return (root / (cfg["source"].get("transactions_file") or cfg["source"]["file"])).exists()


@pytest.mark.parametrize("cfg", ANCHORS, ids=[c["name"] for c in ANCHORS])
def test_features_build_over_the_real_anchor_at_a_workable_speed(cfg):
    """Ticket 07's first line. The measured numbers are in `docs/features.md`; this is the floor.

    Deliberately a floor and not a target: a throughput assertion tuned to one laptop is a flaky
    test. It is here to catch a change that makes the builder quadratic, which is the regression
    that would actually hurt.
    """
    if not anchor_present(cfg):
        pytest.skip(f"{cfg['name']} not downloaded")

    rows = loaders.load_from_config({**cfg, "sample": {"sample_fraction": 0.02}})
    builder = FeatureBuilder(stateful=True)
    start = time.perf_counter()
    X = builder.transform(rows, update=True)
    elapsed = time.perf_counter() - start

    assert X.shape == (len(rows), len(feature_names()))
    assert np.isfinite(X.to_numpy()).all(), "a non-finite feature will poison any scaler"
    assert len(rows) / elapsed > MIN_ROWS_PER_SECOND, (
        f"{cfg['name']}: {len(rows) / elapsed:,.0f} rows/s is below the {MIN_ROWS_PER_SECOND:,} "
        "floor — the builder has probably gone quadratic"
    )


@pytest.mark.parametrize("cfg", ANCHORS, ids=[c["name"] for c in ANCHORS])
def test_the_beneficiary_block_is_alive_on_every_real_anchor(cfg):
    """The one thing ticket 02 said ticket 07 had to get right, asserted on the real files.

    PaySim has no sender history, so a feature set built on the `src` side is built on nothing.
    The check is therefore not "the table has columns" but "the beneficiary columns move".
    """
    if not anchor_present(cfg):
        pytest.skip(f"{cfg['name']} not downloaded")

    rows = loaders.load_from_config({**cfg, "sample": {"sample_fraction": 0.02}})
    builder = FeatureBuilder(stateful=True)
    coverage = builder.coverage(builder.transform(rows, update=True))
    beneficiary = coverage[coverage["group"] == "beneficiary-inbound"]
    assert not beneficiary["dead"].any(), (
        f"{cfg['name']}: dead beneficiary features "
        f"{list(beneficiary[beneficiary['dead']].index)} — the anchor has no fan-in to learn from"
    )
