"""The attack landscape: what we mapped, and the subset the engines actually generate.

`docs/coverage.md` is a pure function of `docs/landscape.yaml` plus anything in
`artifacts/coverage/`. It is never hand-edited.

The load-bearing part is the mirror check. `landscape.yaml` restates the nine generatable vectors
so the document can show mapped and built side by side, and a restatement drifts. So the simulated
block is asserted equal to `vectors.yaml` on every run, field by field, and the build refuses
rather than emitting a document that disagrees with what the code can generate.

    python scripts/build_coverage.py --doc-only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import yaml

ROOT = Path(__file__).resolve().parents[1]
LANDSCAPE = ROOT / "docs/landscape.yaml"
COVERAGE_DIR = ROOT / "artifacts/coverage"
SUMMARY = COVERAGE_DIR / "summary.json"
OUT = ROOT / "docs/coverage.md"

LEVELS = (
    ("mechanism", "Mechanism", "how the money moves"),
    ("enabler", "Enabler", "what is forged before the transaction"),
    ("model-attack", "Model attack", "against the detector, not the victim"),
)


def load_landscape() -> dict:
    return yaml.safe_load(LANDSCAPE.read_text())


def assert_mirror(landscape: dict) -> list[str]:
    """The simulated block must equal vectors.yaml. Raises rather than emitting a stale document."""
    from afl.attack.templates import registry

    truth = registry.load_vectors()
    mirror = {x["id"]: x for x in landscape["simulated"]}

    problems: list[str] = []
    if set(mirror) != set(truth):
        problems.append(
            f"ids differ: landscape has {sorted(set(mirror) - set(truth)) or 'nothing extra'}, "
            f"vectors.yaml has {sorted(set(truth) - set(mirror)) or 'nothing extra'}"
        )
    for vid in sorted(set(mirror) & set(truth)):
        spec, got = truth[vid], mirror[vid]
        for field, actual in (
            ("name", spec.name),
            ("level", spec.level),
            ("engine", spec.engine),
            ("tier", spec.tier),
            ("status", spec.status),
        ):
            if got.get(field) != actual:
                problems.append(f"{vid}.{field}: landscape {got.get(field)!r} != {actual!r}")
    if problems:
        raise SystemExit(
            "docs/landscape.yaml has drifted from afl/attack/templates/vectors.yaml:\n  "
            + "\n  ".join(problems)
            + "\nvectors.yaml is the truth. Fix the mirror, never the other way round."
        )
    return sorted(truth)


def coverage_runs() -> list[dict]:
    """Any standalone audit written to artifacts/coverage/. None is the normal case."""
    if not COVERAGE_DIR.exists():
        return []
    out = []
    for path in sorted(COVERAGE_DIR.glob("*.json")):
        try:
            out.append({"file": path.name, **json.loads(path.read_text())})
        except (OSError, ValueError):
            continue
    return out


def write_summary(landscape: dict) -> dict:
    """The counts, as an artefact, so `make claims` can check the documents against them.

    A number quoted in a document has to fall out of a file. Until this existed the landscape
    count lived only in prose, which is exactly the shape of drift this repository keeps finding.
    """
    from afl.utils.runcard import with_provenance

    sim = {x["id"]: x for x in landscape["simulated"]}
    ident = landscape["identified"]
    payload = {
        "identified_total": len(sim) + len(ident),
        "simulated_built": sum(1 for x in sim.values() if x["status"] == "built"),
        "simulated_template": sum(1 for x in sim.values() if x["status"] == "template"),
        "specified_not_generated": len(ident),
        "by_level": {
            level: sum(1 for x in [*sim.values(), *ident] if x["level"] == level)
            for level, _, _ in LEVELS
        },
    }
    COVERAGE_DIR.mkdir(parents=True, exist_ok=True)
    SUMMARY.write_text(json.dumps(with_provenance(payload), indent=2, sort_keys=True) + "\n")
    return payload


def render(landscape: dict, runs: list[dict]) -> str:
    sim = {x["id"]: x for x in landscape["simulated"]}
    ident = landscape["identified"]
    built = sum(1 for x in sim.values() if x["status"] == "built")
    total = len(sim) + len(ident)

    out = [
        "# Coverage: the landscape we mapped, and the subset that generates",
        "",
        "_Generated by `make coverage` from `docs/landscape.yaml`. Never hand-edited. The",
        "`simulated` block is asserted equal to `afl/attack/templates/vectors.yaml` on every",
        "build, so this document cannot claim a vector the engines cannot produce._",
        "",
        f"**{total} vectors identified, {built} fully simulated.** M1 runs in template mode:",
        "valid traffic of roughly the right shape, without the defining tell. The rest are",
        "specified, not generated.",
        "",
        "Identified means the vector and the surface it would need are specified. These are",
        "demonstrated or specified capabilities, not necessarily mass-exploited patterns. This",
        "document makes no claim about how common any of them is in the field: prevalence is a",
        "separate question, and we did not measure it.",
        "",
        "## What generates today",
        "",
        "| id | vector | level | engine | tier | status |",
        "|---|---|---|---|---|---|",
    ]
    for vid, x in sim.items():
        status = x["status"] if x["status"] == "built" else f"**{x['status']}**"
        out.append(
            f"| `{vid}` | {x['name']} | {x['level']} | {x['engine']} | {x['tier']} | {status} |"
        )

    out += ["", "## What is specified but not generated", ""]
    for key, title, blurb in LEVELS:
        rows = [x for x in ident if x["level"] == key]
        if not rows:
            continue
        out += [
            f"### {title}: {blurb}",
            "",
            "| id | vector | surface | why not built |",
            "|---|---|---|---|",
        ]
        for x in rows:
            out.append(
                f"| `{x['id']}` | {x['name']} | {x.get('surface', '-')} | "
                f"{x.get('why_not', x.get('gap', 'no anchor for this surface'))} |"
            )
        out.append("")

    out += [
        "## Why the gap is what it is",
        "",
        "Every vector above needs an anchor that carries its surface. The four public anchors we",
        "tried are transaction ledgers: they carry payments, not onboarding documents, not voice",
        "calls, not liveness video, not dispute narratives. A vector whose tell lives outside the",
        "transaction stream cannot be simulated against them honestly, and generating it anyway",
        "would produce rows whose only distinguishing feature is that we wrote them.",
        "",
        "That is the same reasoning the commensurability audit applies per batch, one level up.",
    ]

    if runs:
        out += [
            "",
            "## Standalone audits",
            "",
            "| vector | separability | worst field | verdict |",
            "|---|---|---|---|",
        ]
        for r in runs:
            out.append(
                f"| `{r.get('vector', r['file'])}` | {r.get('score', '-')} | "
                f"{r.get('worst', '-')} | {r.get('verdict', '-')} |"
            )
    return "\n".join(out)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--doc-only", action="store_true", help="rebuild the document from the data")
    p.parse_args()

    landscape = load_landscape()
    assert_mirror(landscape)
    counts = write_summary(landscape)
    OUT.write_text(render(landscape, coverage_runs()) + "\n")
    print(f"wrote {SUMMARY.relative_to(ROOT)}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {counts['identified_total']} identified, {counts['simulated_built']} simulated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
