"""The committed baseline: the reference number every later ticket compares against.

Same discipline as `artifacts/splits/` — *the config holds the inputs, the artefact holds the
decision*. A baseline that lives in a README paragraph is a baseline that quietly drifts; a
baseline that lives in a committed file with the backend, the params, the split digest and the
seed beside it is one a later ticket can be measured against.

Regenerated by `scripts/build_baseline.py` (`make baseline`), never hand-edited.

The one rule this module enforces in code rather than in prose: **accuracy and ROC-AUC do not
appear in a reported metric block.** At a 0.13% base rate both are dominated by the negatives, so
a model that catches nothing still scores well on them. `save` refuses a payload containing
either, which is a cheaper guard than remembering.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from afl.utils.runcard import with_provenance

#: Bump when the fields change shape, so an old file fails loudly instead of being read with the
#: wrong meaning.
BASELINE_ARTEFACT_VERSION = 1

DEFAULT_BASELINE_DIR = Path(os.getenv("AFL_BASELINE_DIR", "artifacts/detector"))

#: Never a headline number here. See the module docstring; `afl/evaluation/protocol.py` says why.
#: Matched exactly or as a `_`-suffix, which is why the bare word `auc` is not in the list:
#: `pr_auc` is one of the three metrics this project *does* report, and a rule that banned every
#: name ending in "auc" would ban the reference number itself.
FORBIDDEN_METRICS = ("accuracy", "roc_auc", "auroc", "roc")

#: The three the protocol reports, all at one operating point.
REQUIRED_METRICS = ("pr_auc", "recall_at_fixed_fpr", "precision_at_k")


class ForbiddenMetric(ValueError):
    """Raised when a reported metric block contains accuracy or ROC-AUC."""


def assert_no_forbidden_metrics(payload: Any, path: str = "metrics") -> None:
    """Walk a reported block and refuse accuracy / ROC-AUC by name, at any depth."""
    if isinstance(payload, dict):
        for key, value in payload.items():
            lowered = str(key).lower()
            if any(bad == lowered or lowered.endswith(f"_{bad}") for bad in FORBIDDEN_METRICS):
                raise ForbiddenMetric(
                    f"{path}.{key} is a headline metric this project does not report — at a "
                    "0.13% base rate accuracy and ROC-AUC are dominated by the negatives, so a "
                    "detector that catches nothing still scores well on both"
                )
            assert_no_forbidden_metrics(value, f"{path}.{key}")
    elif isinstance(payload, list):
        for i, value in enumerate(payload):
            assert_no_forbidden_metrics(value, f"{path}[{i}]")


@dataclass(frozen=True)
class Baseline:
    """One anchor's supervised reference, at one fixed operating point.

    `metrics` is keyed by variant — `"tuned"` is the reference, `"default"` is the same detector
    at the stock params, and the gap between them is the evidence that the search was not a
    formality. Both are scored on the same committed out-of-time test window.
    """

    dataset: str
    operating_point: dict[str, Any]
    backend: dict[str, Any]
    params: dict[str, Any]
    metrics: dict[str, dict[str, Any]]
    tuning: dict[str, Any] = field(default_factory=dict)
    data: dict[str, Any] = field(default_factory=dict)
    split: dict[str, Any] = field(default_factory=dict)
    seed: int = 1337
    meta: dict[str, Any] = field(default_factory=dict)
    version: int = BASELINE_ARTEFACT_VERSION

    def __post_init__(self) -> None:
        assert_no_forbidden_metrics(self.metrics)
        missing = [m for m in REQUIRED_METRICS if m not in (self.headline or {})]
        if missing:
            raise ValueError(f"{self.dataset}: reference metrics are missing {missing}")

    @property
    def headline(self) -> dict[str, Any]:
        """The reference row: the tuned detector on the committed out-of-time test window."""
        return self.metrics.get("tuned", {})

    @property
    def backend_name(self) -> str:
        return str(self.backend.get("name", "unknown"))

    def summary(self) -> str:
        """One line, in the form every later ticket quotes it in."""
        m = self.headline
        return (
            f"{self.dataset}: PR-AUC {m['pr_auc']:.3f}  "
            f"recall@{float(self.operating_point['fixed_fpr']):.0%}FPR "
            f"{m['recall_at_fixed_fpr']:.3f}  "
            f"precision@{int(self.operating_point['k'])} {m['precision_at_k']:.2f}  "
            f"[{self.backend_name}]"
        )

    # ── round trip ──────────────────────────────────────────────────────────────
    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "dataset": self.dataset,
            "seed": self.seed,
            "operating_point": self.operating_point,
            "backend": self.backend,
            "params": self.params,
            "split": self.split,
            "data": self.data,
            "tuning": self.tuning,
            "metrics": self.metrics,
            "meta": self.meta,
        }

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> Baseline:
        if int(raw.get("version", 0)) != BASELINE_ARTEFACT_VERSION:
            raise ValueError(
                f"baseline artefact version {raw.get('version')} != {BASELINE_ARTEFACT_VERSION}; "
                "rebuild it with scripts/build_baseline.py rather than reading it as-is"
            )
        return cls(
            dataset=raw["dataset"],
            operating_point=raw["operating_point"],
            backend=raw["backend"],
            params=raw["params"],
            metrics=raw["metrics"],
            tuning=raw.get("tuning", {}),
            data=raw.get("data", {}),
            split=raw.get("split", {}),
            seed=int(raw.get("seed", 1337)),
            meta=raw.get("meta", {}),
        )

    def save(self, directory: str | Path = DEFAULT_BASELINE_DIR) -> Path:
        path = Path(directory) / f"{self.dataset}.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(with_provenance(self.to_dict()), indent=2, default=str) + "\n")
        return path

    @classmethod
    def load(cls, dataset: str, directory: str | Path = DEFAULT_BASELINE_DIR) -> Baseline:
        path = Path(directory) / f"{dataset}.json"
        if not path.exists():
            raise FileNotFoundError(
                f"no committed baseline for {dataset!r} at {path} — run "
                "`make baseline` once and commit the result"
            )
        return cls.from_dict(json.loads(path.read_text()))


def load_all(directory: str | Path = DEFAULT_BASELINE_DIR) -> dict[str, Baseline]:
    """Every committed baseline on disk, keyed by dataset."""
    directory = Path(directory)
    if not directory.exists():
        return {}
    out: dict[str, Baseline] = {}
    for path in sorted(directory.glob("*.json")):
        out[path.stem] = Baseline.from_dict(json.loads(path.read_text()))
    return out


def tuned_params(
    dataset: str, directory: str | Path = DEFAULT_BASELINE_DIR
) -> tuple[dict[str, Any], str]:
    """The committed params for an anchor, and where they came from.

    Returns `({}, reason)` when there is no baseline yet, so a run on a fresh clone — or on the
    synthetic default, which has no committed baseline by design — falls back to the configured
    defaults instead of failing.
    """
    path = Path(directory) / f"{dataset}.json"
    try:
        return dict(Baseline.load(dataset, directory).params), str(path)
    except (FileNotFoundError, ValueError, KeyError) as e:
        return {}, f"default ({type(e).__name__}: no usable baseline at {path})"
